### ISSUE TITLE
Please provide a binary release for linux or provide specific instructions for setting up build environment.

### ISSUE THREAD

**Issue by Poikilos** [kodi-game/game.libretro#89]
- OS: Drauger OS 7.5.1 Zombi (based on Ubuntu)

I am trying to compile but I've had quite a bit ot trouble compiling Kodi. The readme for game.libretro says:
> First, make sure Kodi's add-on build system is installed somewhere. You can perform a system install (to /usr/local) or a local install (I prefer $HOME/kodi). Specify this when you build Kodi:
> `./bootstrap`
> `./configure --prefix=$HOME/kodi`
> `make`
> `make install`

And if I go to the latest source of Kodi at https://github.com/xbmc/xbmc and clone it, there is no ./bootstrap file so the command is not found.

I am not sure a release will work for me because the game.libretro 2.0.0 release says "Requires Kodi 19 Matrix Version of "Oct. 26, 2019" or later!" and I am stuck on Kodi 18. Is there any version of game.libretro I may be able to use or compile? If I install the flatpak version of Kodi (even as root), it doesn't show as an option for the session in lightdm. If I try to bulid Kodi according to its compiling documentationI can't due to the error at the bottom of this: <https://pastebin.com/fXMfSA4m>.

Is there some easier way to compile game.libretro or get it into Kodi? Must I compile Kodi? Maybe I will try the deb-src repo next to compile it easier. if you think it is even worth it since it is v18.

Thanks

**Comment by lrusak** [comment]
The repo is organized in branches that correspond to the Kodi version. For Kodi 18 you can build the version here https://github.com/kodi-game/game.libretro/tree/Leia

Yes you need to build Kodi from source as the headers are required.

You can find the Kodi build instructions for v18 here https://github.com/xbmc/xbmc/blob/Leia/docs/README.Linux.md

Otherwise please make a forum post if you need further help as this is a bug tracker. Thanks. https://forum.kodi.tv/

**Comment by garbear** [comment]
Also @poikilos thanks for pointing out the stale documentation. Since it was written we've moved from bootstrap/autotools to CMake. I'll update the README when I get a chance.
